export const FETCH_PETS = "FETCH_PETS";
export const ADD_DOWNLOAD_PET = "ADD_PET";
export const REMOVE_DOWNLOAD_PET = "REMOVE_PET";
export const FILTER_PETS = "FILTER_PETS";
export const DOWNLOAD_ALL_PETS = "DOWNLOAD_ALL_PETS";
export const REMOVE_ALL_PETS = "REMOVE_ALL_PETS";
